# Dependencies
markdown: kramdown
highlighter: rouge

# gems
plugins:
  - jekyll-feed
  # - jekyll-gist
  # - jekyll-redirect-from
  # - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile.html,
    Gemfile.lock,
    data,
    convert,
    convert.sh
  ]

# Site meta
title: Cookbook
tagline: 'All the Food'
description: 'Family Recipes.'
keywords: 'food'
url: https://github.com/darkoverlordofdata
assets: /assets
theme: minima

baseurl: "/cookbook" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: overlordofdata
github_username:  darkoverlordofdata


collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/