#!/usr/bin/env bash
pandoc -o "_recipes/Asian Orange Chicken.markdown" "data/docx/Asian Orange Chicken.docx"
pandoc -o "_recipes/Asian Salad Dressing.markdown" "data/docx/Asian Salad Dressing.docx"
pandoc -o "_recipes/Beef Chuck Pot Roast.markdown" "data/docx/Beef Chuck Pot Roast.docx"
pandoc -o "_recipes/Chicken Broccoli Stir Fry.markdown" "data/docx/Chicken Broccoli Stir Fry.docx"
pandoc -o "_recipes/Chilli con carne.markdown" "data/docx/Chilli con carne.docx"
pandoc -o "_recipes/Ham Buns.markdown" "data/docx/Ham Buns.docx"
pandoc -o "_recipes/Hot _ Sour Soup.markdown" "data/docx/Hot _ Sour Soup.docx"
pandoc -o "_recipes/Italian Peas, Onions, and Pancetta.markdown" "data/docx/Italian Peas, Onions, and Pancetta.docx"
pandoc -o "_recipes/Itallian Meatballs.markdown" "data/docx/Itallian Meatballs.docx"
pandoc -o "_recipes/J.D._s BBQ Sauce.markdown" "data/docx/J.D._s BBQ Sauce.docx"
pandoc -o "_recipes/Katsu Sauce.markdown" "data/docx/Katsu Sauce.docx"
pandoc -o "_recipes/Lasagna.markdown" "data/docx/Lasagna.docx"
pandoc -o "_recipes/Mexican Tartar Sauce.markdown" "data/docx/Mexican Tartar Sauce.docx"
pandoc -o "_recipes/Pancakes.markdown" "data/docx/Pancakes.docx"
pandoc -o "_recipes/Potato Salad.markdown" "data/docx/Potato Salad.docx"
pandoc -o "_recipes/Rib Juice.markdown" "data/docx/Rib Juice.docx"
pandoc -o "_recipes/Rood Wings.markdown" "data/docx/Rood Wings.docx"
pandoc -o "_recipes/Sweet and Sour Green Beans.markdown" "data/docx/Sweet and Sour Green Beans.docx"
pandoc -o "_recipes/Waffles.markdown" "data/docx/Waffles.docx"

# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
# pandoc -o "_recipes/.markdown" "data/odt/.odt"
